version: '3.9'
services:
  backend-app:
    container_name: backend-code
    image: backend-code
    build: ../
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    environment:
      - POSTGRES_DB=hospitalReport_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
  postgresqldb:
    image: postgres:9.5
    restart: always
    container_name: postgresqldb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hospitalReport_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s






